### ISSUE TITLE
Current Directory during Export-ArXivArchive

### ISSUE THREAD

**Issue by ihincks** [cgranade/posh-tex#17]
I'm running into the following problem: my `Export-ArXiv.ps1` file is in `./` and my tex file is in `./tex`. The tex file includes a package `revquantum.sty` which is stored locally, also in `./tex`. To make `latexmk` run, my local directory needs to be `./tex`. If I am one folder back (as is the case with `Export-ArXivArchive`), then pdflatex cannot find `revquantum` and fails. 

Is there a workaround? Or maybe `Export-ArXivArchive` should temporarily switch into the folder it is compiling?

**Comment by cgranade** [comment]
This seems to work now, with #18 merged in. Thanks for the help!
